### PR TITLE
fix: register type with prefix

### LINKED ISSUE #51: gob.Register panics on model types conflict
**Actual behavior** A clear and concise description of what the bug is.

When running this uber mockgen in a codebase with reference to the golang mockgen, the reflect program would panic on the `gob.Register` call:

```
panic: gob: registering duplicate types for "*model.ArrayType": *model.ArrayType != *model.ArrayType

goroutine 1 [running]:
encoding/gob.RegisterName({0x10fad4f, 0x10}, {0x110b460, 0xc000010468})
        /usr/local/go/src/encoding/gob/type.go:820 +0x3f4
encoding/gob.Register({0x110b460, 0xc000010468})
        /usr/local/go/src/encoding/gob/type.go:874 +0x1c5
github.com/golang/mock/mockgen/model.init.0()
        $HOME/workshop/go/pkg/mod/github.com/golang/mock@v1.6.0/mockgen/model/model.go:146 +0x39
panic: gob: registering duplicate types for "*model.ArrayType": *model.ArrayType != *model.ArrayType
...
```

**Expected behavior** A clear and concise description of what you expected to
happen.

This is because in our code base (or similar code base created before go mod area) contains import path like this:

```
_ "github.com/golang/mock/mockgen/model"
``` 

This call will register the model types with the same name, and result in gob panic. This import call is suggested by golang mockgen as a workaround for vendor usage:

https://github.com/golang/mock#reflect-vendoring-error

I believe this would be a blocker for migrating from golang mockgen as upstream libraries might have such import path, and it would take time to migrate all these upstream libraries as it requires multiple steps.

Therefore, I would like to propose a fix to register these model types with a prefix.

**To Reproduce** Steps to reproduce the behavior

To produce this issue, please check out this commit: https://github.com/bcho/gomock-migrate/tree/4148048b8a313fa0be6164d1cdcdc941e523c0c1 

I have a fix poc in this commit: https://github.com/bcho/gomock-migrate/tree/2de73982ee899e4e0a3986a021b584c08feb3e5f , which updated the uber gomock to use the fixed model in my local fork. 

**Additional Information**

-   gomock mode (reflect or source): reflect
-   gomock version or git ref: `0.2.0`
-   golang version: go version go1.20.2 darwin/amd64

**Triage Notes for the Maintainers**

### PR DESCRIPTION
**Pull request by bcho**
fix #51

### CODE REVIEW

File: mockgen/model/model.go [hunk 1]
```diff
@@ -147,12 +147,12 @@ type Type interface {
 }
 
 func init() {
-	gob.Register(&ArrayType{})
-	gob.Register(&ChanType{})
-	gob.Register(&FuncType{})
-	gob.Register(&MapType{})
-	gob.Register(&NamedType{})
-	gob.Register(&PointerType{})
+	gob.RegisterName(pkgPath+".ArrayType", &ArrayType{})
```
Comment (r-hang) [inline mockgen/model/model.go:150]: Should the registered named be prefixed with a "*"? From my understanding gob.Register is only misbehaving (i.e. no fully qualifying) for named pointer types.

Comment (bcho) [reply mockgen/model/model.go:150]: From gob's implementation, the registered type will be firstly reflected for the actual type (userType), then stored in two map, with `<name, type>` and `<type, name>` pairs: https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/encoding/gob/type.go;l=836-844;drc=f80e270babcddd28e29a52c1cb834ffed427bd8a

In the encode part, encoder will use the same `userType` again to reflect the actual type, and look up the name: https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/encoding/gob/encode.go;l=400-405;drc=6a51c000def084b820756f066397fd2505e75e25

In the decode part, a similar but reverse process will be used for looking up type by name: https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/encoding/gob/decode.go;l=699-704;drc=f62c9701b4bc61da6a5f4db8ef81d816f112430e

The default `gob.Register` call infers the type name with this: https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/encoding/gob/type.go;l=854-856;drc=f80e270babcddd28e29a52c1cb834ffed427bd8a (without calling user type etc) . For instance, giving a pointer to `MapType` from two different packages, the name here will be inferred as the same value (yes it will have a `*` prefix as it's a pointer type). As a result, we will see panic in later register when using like issue #51  . 

The fix here is to add a qualified prefix to the value type, so we can avoid the panic on register. But to gob, it's just an unique identifier. Or, we can define it as something like `{pkgPath}.*MapType`. Let me know your thought!

File: mockgen/model/model.go [hunk 2]
```diff
@@ -147,12 +147,12 @@ type Type interface {
...
+	gob.RegisterName(pkgPath+".ChanType", &ChanType{})
+	gob.RegisterName(pkgPath+".FuncType", &FuncType{})
+	gob.RegisterName(pkgPath+".MapType", &MapType{})
+	gob.RegisterName(pkgPath+".NamedType", &NamedType{})
+	gob.RegisterName(pkgPath+".PointerType", &PointerType{})
```
Comment (moisesvega) [inline mockgen/model/model.go:155]: Can we add a comment why we are using `RegisterName` ?

**Review by sywhang — APPROVED** [review]
Thanks for fixing this @bcho ! This looks good to me, other than @moisesvega 's suggestion on adding a brief comment on top of init explaining that this is needed for projects that are using both golang/mock and uber/mock.

File: mockgen/model/model.go (hunk 2 above)
Comment (bcho) [reply mockgen/model/model.go:157]: Added a comment, @moisesvega / @sywhang  PTAL

**Review by sywhang — APPROVED** [review]

**Comment by bcho** [comment]
@sywhang thanks for merging this, any plan to create a new release? Our team needs this to migrate from golang/mock to uber/mock :)

**Comment by Tulzke** [comment]
> @sywhang thanks for merging this, any plan to create a new release? Our team needs this to migrate from golang/mock to uber/mock :)

+1
